// <auto-generated />
using System;
using BitNest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BitNest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319021858_Phase7AccessFoundation")]
    partial class Phase7AccessFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BitNest.Models.ChunkMetadata", b =>
                {
                    b.Property<byte[]>("Hash")
                        .HasColumnType("bytea");

                    b.HasKey("Hash");

                    b.ToTable("Chunks");
                });

            modelBuilder.Entity("BitNest.Models.FileChunk", b =>
                {
                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("ChunkHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Order", "FileId");

                    b.HasIndex("ChunkHash");

                    b.HasIndex("FileId");

                    b.ToTable("FileChunks");
                });

            modelBuilder.Entity("BitNest.Models.FileGrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<int>("GrantedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("GrantedUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GrantedByUserId");

                    b.HasIndex("GrantedUserId");

                    b.HasIndex("FileId", "GrantedUserId")
                        .IsUnique();

                    b.ToTable("FileGrants");
                });

            modelBuilder.Entity("BitNest.Models.FileMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Extention")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsChunked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUploaded")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("integer");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("BitNest.Models.RefreshSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RememberMe")
                        .HasColumnType("boolean");

                    b.Property<int?>("ReplacedBySessionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("RefreshSessions");
                });

            modelBuilder.Entity("BitNest.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSignInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BitNest.Models.FileChunk", b =>
                {
                    b.HasOne("BitNest.Models.ChunkMetadata", "Chunk")
                        .WithMany("Files")
                        .HasForeignKey("ChunkHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitNest.Models.FileMetadata", "File")
                        .WithMany("Chunks")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chunk");

                    b.Navigation("File");
                });

            modelBuilder.Entity("BitNest.Models.FileGrant", b =>
                {
                    b.HasOne("BitNest.Models.FileMetadata", "File")
                        .WithMany("Grants")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitNest.Models.User", "GrantedByUser")
                        .WithMany("IssuedFileGrants")
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BitNest.Models.User", "GrantedUser")
                        .WithMany("GrantedFiles")
                        .HasForeignKey("GrantedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("GrantedByUser");

                    b.Navigation("GrantedUser");
                });

            modelBuilder.Entity("BitNest.Models.FileMetadata", b =>
                {
                    b.HasOne("BitNest.Models.User", "OwnerUser")
                        .WithMany("OwnedFiles")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("BitNest.Models.RefreshSession", b =>
                {
                    b.HasOne("BitNest.Models.User", "User")
                        .WithMany("RefreshSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BitNest.Models.ChunkMetadata", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("BitNest.Models.FileMetadata", b =>
                {
                    b.Navigation("Chunks");

                    b.Navigation("Grants");
                });

            modelBuilder.Entity("BitNest.Models.User", b =>
                {
                    b.Navigation("GrantedFiles");

                    b.Navigation("IssuedFileGrants");

                    b.Navigation("OwnedFiles");

                    b.Navigation("RefreshSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
