// <auto-generated />
using BitNest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BitNest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260128231213_ChunkStorageUpdated")]
    partial class ChunkStorageUpdated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BitNest.Models.ChunkMetadata", b =>
                {
                    b.Property<byte[]>("Hash")
                        .HasColumnType("bytea");

                    b.HasKey("Hash");

                    b.ToTable("Chunks");
                });

            modelBuilder.Entity("BitNest.Models.FileMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Extention")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsChunked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUploaded")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("ChunkMetadataFileMetadata", b =>
                {
                    b.Property<byte[]>("ChunksHash")
                        .HasColumnType("bytea");

                    b.Property<int>("FilesId")
                        .HasColumnType("integer");

                    b.HasKey("ChunksHash", "FilesId");

                    b.HasIndex("FilesId");

                    b.ToTable("ChunkMetadataFileMetadata");
                });

            modelBuilder.Entity("ChunkMetadataFileMetadata", b =>
                {
                    b.HasOne("BitNest.Models.ChunkMetadata", null)
                        .WithMany()
                        .HasForeignKey("ChunksHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitNest.Models.FileMetadata", null)
                        .WithMany()
                        .HasForeignKey("FilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
